"""
Genesis QA - Scenario Generator Module
========================================
Generates structured, configurable test scenarios suitable for running
against the scan pipeline.

Typical usage:
    generator = ScenarioGenerator()
    scenarios = generator.generate(count=10)
"""

from __future__ import annotations

import json
import logging
import random
import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------


class ScenarioCategory(Enum):
    """High-level category a scenario belongs to."""

    FUNCTIONAL = "functional"
    SECURITY = "security"
    PERFORMANCE = "performance"
    COMPLIANCE = "compliance"
    INTEGRATION = "integration"


class ScenarioSeverity(Enum):
    """Severity / priority level of a test scenario."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass
class ScenarioStep:
    """A single step within a test scenario."""

    action: str
    expected: str
    params: dict[str, Any] = field(default_factory=dict)


@dataclass
class Scenario:
    """A complete test scenario generated by the ScenarioGenerator.

    Attributes:
        uid:         Unique scenario identifier.
        name:        Human-readable scenario name.
        category:    Functional / security / performance / etc.
        severity:    Priority / severity rating.
        target:      The target endpoint, URL, or component under test.
        description: Short description of what the scenario validates.
        steps:       Ordered list of actions and expected outcomes.
        tags:        Arbitrary labels for filtering / grouping.
        metadata:    Generation-time diagnostics (template used, seed, etc.).
        created_at:  ISO-formatted UTC timestamp.
    """

    uid: str = ""
    name: str = ""
    category: ScenarioCategory = ScenarioCategory.FUNCTIONAL
    severity: ScenarioSeverity = ScenarioSeverity.MEDIUM
    target: str = ""
    description: str = ""
    steps: list[ScenarioStep] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = ""

    def __post_init__(self) -> None:
        if not self.uid:
            self.uid = uuid.uuid4().hex[:12]
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat()

    def to_dict(self) -> dict[str, Any]:
        """Serialize the scenario to a JSON-safe dictionary."""
        d = asdict(self)
        d["category"] = self.category.value
        d["severity"] = self.severity.value
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Scenario:
        """Deserialize a dictionary back into a Scenario."""
        data = dict(data)
        data["category"] = ScenarioCategory(data.get("category", "functional"))
        data["severity"] = ScenarioSeverity(data.get("severity", "medium"))
        data["steps"] = [ScenarioStep(**s) for s in data.get("steps", [])]
        return cls(**data)


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


class ScenarioGenerator:
    """Generates test scenarios from built-in templates and rules.

    The generator can produce scenarios in several categories, optionally
    constrained by count, target, tags, or a random seed for reproducibility.

    Attributes:
        seed:       Random seed for reproducible generation (default: None).
        templates:  Dict mapping category names to their scenario templates.
        rng:        Internal ``random.Random`` instance.
    """

    # ------------------------------------------------------------------
    # Built-in scenario templates
    # ------------------------------------------------------------------

    TEMPLATES: dict[str, list[dict[str, Any]]] = {
        "functional": [
            {
                "name": "Basic health check for {target}",
                "description": "Verify that {target} responds with a 2xx status code.",
                "steps": [
                    {
                        "action": f"Send GET request to {{target}}",
                        "expected": "HTTP 200 OK",
                        "params": {"method": "GET", "expected_status": 200},
                    },
                ],
                "tags": ["smoke", "health"],
            },
            {
                "name": "Form submission on {target}",
                "description": "Submit a valid form payload to {target}.",
                "steps": [
                    {
                        "action": f"POST valid payload to {{target}}",
                        "expected": "HTTP 201 or 200 with success body",
                        "params": {"method": "POST", "expected_status": [200, 201]},
                    },
                    {
                        "action": "Verify response contains expected confirmation",
                        "expected": "Success message or redirect present",
                        "params": {},
                    },
                ],
                "tags": ["form", "crud"],
            },
            {
                "name": "Resource listing on {target}",
                "description": "Retrieve a paginated list from {target}.",
                "steps": [
                    {
                        "action": f"GET {{target}} with pagination params",
                        "expected": "HTTP 200 with list of items",
                        "params": {
                            "method": "GET",
                            "query_params": {"page": 1, "per_page": 20},
                        },
                    },
                ],
                "tags": ["list", "pagination"],
            },
        ],
        "security": [
            {
                "name": "SQL injection probe on {target}",
                "description": "Attempt basic SQL injection on {target}.",
                "steps": [
                    {
                        "action": f"Send request with payload: {{payload}}",
                        "expected": "No SQL error leaked",
                        "params": {"payload": "' OR '1'='1"},
                    },
                ],
                "tags": ["injection", "sqli"],
            },
            {
                "name": "XSS reflection check on {target}",
                "description": "Check if payloads are reflected unsanitised.",
                "steps": [
                    {
                        "action": f"Send request with payload: {{payload}}",
                        "expected": "Payload is escaped or blocked",
                        "params": {"payload": "<script>alert(1)</script>"},
                    },
                ],
                "tags": ["xss", "injection"],
            },
            {
                "name": "Auth bypass attempt on {target}",
                "description": "Access {target} without authentication credentials.",
                "steps": [
                    {
                        "action": f"GET {{target}} without auth header",
                        "expected": "HTTP 401 or 403",
                        "params": {"method": "GET", "expected_status": [401, 403]},
                    },
                ],
                "tags": ["auth", "bypass"],
            },
        ],
        "performance": [
            {
                "name": "Response time check for {target}",
                "description": "Measure response time of {target} under baseline load.",
                "steps": [
                    {
                        "action": f"GET {{target}}",
                        "expected": "Response under 2000 ms",
                        "params": {"method": "GET", "max_duration_ms": 2000},
                    },
                ],
                "tags": ["latency", "baseline"],
            },
            {
                "name": "Concurrent requests on {target}",
                "description": "Send {concurrency} simultaneous requests to {target}.",
                "steps": [
                    {
                        "action": f"Fire {{concurrency}} concurrent GET requests",
                        "expected": "All respond successfully, no crashes",
                        "params": {"method": "GET", "concurrency": 10},
                    },
                ],
                "tags": ["concurrency", "stress"],
            },
        ],
        "compliance": [
            {
                "name": "GDPR data exposure check on {target}",
                "description": "Verify that {target} does not leak PII in responses.",
                "steps": [
                    {
                        "action": f"GET {{target}} and inspect response body",
                        "expected": "No email / phone / SSN patterns found",
                        "params": {"method": "GET", "patterns_to_check": ["email", "phone", "ssn"]},
                    },
                ],
                "tags": ["gdpr", "compliance"],
            },
        ],
        "integration": [
            {
                "name": "Upstream dependency health for {target}",
                "description": "Verify {target} can reach its upstream dependencies.",
                "steps": [
                    {
                        "action": f"GET {{target}}/health/dependencies",
                        "expected": "All upstream services report healthy",
                        "params": {"method": "GET", "expected_status": 200},
                    },
                ],
                "tags": ["integration", "health"],
            },
            {
                "name": "Webhook delivery from {target}",
                "description": "Trigger a webhook event on {target} and confirm delivery.",
                "steps": [
                    {
                        "action": f"POST webhook event to {{target}}",
                        "expected": "HTTP 202 Accepted",
                        "params": {"method": "POST", "expected_status": 202},
                    },
                    {
                        "action": "Verify webhook receiver was called",
                        "expected": "Receiver confirms event receipt",
                        "params": {},
                    },
                ],
                "tags": ["webhook", "integration"],
            },
        ],
    }

    DEFAULT_SEVERITY: dict[str, ScenarioSeverity] = {
        "functional": ScenarioSeverity.MEDIUM,
        "security": ScenarioSeverity.HIGH,
        "performance": ScenarioSeverity.LOW,
        "compliance": ScenarioSeverity.MEDIUM,
        "integration": ScenarioSeverity.MEDIUM,
    }

    def __init__(
        self,
        *,
        seed: Optional[int] = None,
        templates: Optional[dict[str, list[dict[str, Any]]]] = None,
    ) -> None:
        self.seed = seed
        self.rng = random.Random(seed)
        self.templates = templates or self.TEMPLATES

        logger.debug(
            "ScenarioGenerator initialised (seed=%s, templates=%d categories)",
            seed,
            len(self.templates),
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(
        self,
        count: int = 5,
        *,
        target: str = "/api/endpoint",
        categories: Optional[list[ScenarioCategory]] = None,
        severity: Optional[ScenarioSeverity] = None,
        tags: Optional[list[str]] = None,
    ) -> list[Scenario]:
        """Generate a list of test scenarios.

        Args:
            count:      Number of scenarios to produce (default 5).
            target:     Target URL or component name to bake into scenarios.
            categories: Filter by one or more ``ScenarioCategory`` values.
                        If ``None``, all categories are eligible.
            severity:   If set, only templates whose default severity matches
                        are used.
            tags:       If set, only templates containing **any** of the
                        given tags are used.

        Returns:
            A list of ``Scenario`` instances.

        Raises:
            ValueError: If ``count`` is less than 1.
        """
        if count < 1:
            raise ValueError("count must be >= 1")

        logger.info(
            "Generating %d scenarios (target=%s, categories=%s, severity=%s, tags=%s)",
            count,
            target,
            categories,
            severity,
            tags,
        )

        # Flatten eligible templates -------------------------------------------------
        candidates: list[tuple[ScenarioCategory, dict[str, Any]]] = []

        for cat_name, templates in self.templates.items():
            cat_enum = ScenarioCategory(cat_name)

            if categories and cat_enum not in categories:
                continue

            for template in templates:
                t_sev = self.DEFAULT_SEVERITY.get(cat_name, ScenarioSeverity.MEDIUM)

                if severity and t_sev != severity:
                    continue

                if tags:
                    ttags = [t.lower() for t in template.get("tags", [])]
                    if not any(t.lower() in ttags for t in tags):
                        continue

                candidates.append((cat_enum, template))

        if not candidates:
            logger.warning("No templates matched the given filters — returning empty list")
            return []

        # Sample and build scenarios -------------------------------------------------
        chosen: list[tuple[ScenarioCategory, dict[str, Any]]]
        if len(candidates) <= count:
            chosen = candidates[:]
            self.rng.shuffle(chosen)
        else:
            chosen = self.rng.sample(candidates, k=count)

        scenarios: list[Scenario] = []
        for cat, template in chosen:
            scenario = self._build_scenario(cat, template, target)
            scenarios.append(scenario)

        logger.info("Generated %d scenarios", len(scenarios))
        return scenarios

    def generate_from_file(
        self,
        path: str | Path,
        *,
        target: str = "/api/endpoint",
        **kwargs: Any,
    ) -> list[Scenario]:
        """Load templates from a JSON file and generate scenarios.

        The JSON file must contain a dict with category names as keys,
        each value being a list of template dicts (same structure as
        ``TEMPLATES``).

        Args:
            path:   Path to a JSON template file.
            target: Target to inject into templates.
            **kwargs: Forwarded to ``generate()``.

        Returns:
            List of generated ``Scenario`` instances.

        Raises:
            FileNotFoundError: If the path does not exist.
            ValueError:       If the JSON is malformed.
        """
        p = Path(path)
        if not p.exists():
            raise FileNotFoundError(f"Template file not found: {p.resolve()}")

        try:
            raw = p.read_text(encoding="utf-8")
            data: dict[str, list[dict[str, Any]]] = json.loads(raw)
        except (json.JSONDecodeError, OSError) as exc:
            raise ValueError(f"Failed to parse template file: {exc}") from exc

        logger.info("Loaded %d template categories from %s", len(data), p.resolve())
        return self.generate(count=len(data) * 3, target=target, **kwargs)

    def export_to_json(
        self,
        scenarios: list[Scenario],
        path: str | Path,
        *,
        indent: int = 2,
    ) -> Path:
        """Export a list of scenarios to a JSON file.

        Args:
            scenarios: Scenarios to export.
            path:      Destination file path.
            indent:    JSON indentation level (default 2).

        Returns:
            The resolved ``Path`` to the written file.
        """
        p = Path(path)
        data = [s.to_dict() for s in scenarios]
        p.write_text(json.dumps(data, indent=indent, default=str), encoding="utf-8")
        logger.info("Exported %d scenarios to %s", len(scenarios), p.resolve())
        return p.resolve()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_scenario(
        self,
        category: ScenarioCategory,
        template: dict[str, Any],
        target: str,
    ) -> Scenario:
        """Instantiate a ``Scenario`` from a template dict."""
        name = template["name"].format(target=target)
        description = template["description"].format(target=target)

        steps: list[ScenarioStep] = []
        for step_def in template.get("steps", []):
            action = step_def["action"].format(target=target, payload=self._random_payload())
            steps.append(
                ScenarioStep(
                    action=action,
                    expected=step_def["expected"],
                    params=dict(step_def.get("params", {})),
                )
            )

        ttags = list(template.get("tags", []))
        severity = self.DEFAULT_SEVERITY.get(category.value, ScenarioSeverity.MEDIUM)

        return Scenario(
            name=name,
            category=category,
            severity=severity,
            target=target,
            description=description,
            steps=steps,
            tags=ttags,
            metadata={
                "generator": "ScenarioGenerator",
                "seed": self.seed,
                "template_name": template.get("name", ""),
            },
        )

    def _random_payload(self) -> str:
        """Generate a random payload string for injection templates."""
        payloads = [
            "' OR '1'='1",
            "<script>alert(1)</script>",
            "../../etc/passwd",
            "'; DROP TABLE users; --",
            "\" ONMOUSEOVER=\"alert(1)\"",
        ]
        return self.rng.choice(payloads)
